patch:
  menu/page_size: 9
  schema_list:
    - { schema: double_pinyin_flypy }
  key_binder/bindings/+:
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }
